choderalab/perses

- perses/annihilation/ncmc_switching.py
- perses/tests/test_ncmc.py
Addresses #15 to show that we can handle nsteps = 0 (instantaneous switching).
> Test NCMC switching for nsteps = 0, 1, and 50 steps

- examples/rjmc/run_example.py
- perses/annihilation/alchemical_engine.py
- perses/annihilation/ncmc_switching.py
- perses/tests/test_elimination.py
- perses/tests/test_ncmc.py
In preparation for the changes in #32, I added more NCMC tests and found a couple of bugs:
* Direction (`insert/delete`) was being ignored
* NCMC did not reduce to instantaneous Monte Carlo when number of switching steps was 0
Now, `nsteps = 0, 1, 50` are all tested for a harmonic oscillator and a null transformation for alanine dipeptide in vacuum.
> Fixed a major bug in NCMCEngine and added more NCMC tests

- perses/rjmc/geometry.py
- perses/rjmc/topology_proposal.py
- perses/tests/test_geometry_engine.py
In the early stages of refactoring the geometry engine stuff. The plan thus far is:
* Modularize more (subclass of the general `GeometryEngine` that handles stuff required for all forcefield-based geometry engines, then a subclass of that for the specific idea we discussed)
* New implementation where `p(rho`) is calculated from `p(rho| thetas, rhos)` as discussed in #9 
* Calculate `logp` separately from proposal to allow schemes discussed in #43 
* Switch to using `parmed` to sort through the `system` and `topologies`
> Refactor geometry engine

- perses/tests/test_ncmc_integrator.py
The sign error was present in the harmonic oscillator NCMC tests as well.
I've also added more iterations to hopefully more readily detect issues.
> Fix NCMC harmonic oscillator tests

- perses/annihilation/ncmc_switching.py
- perses/tests/test_elimination.py
- perses/tests/test_geometry_engine.py
- perses/tests/test_sampler.py
Attempting to address #77.  NCMC switching now returns a potential energy that can be used in computing this additional contribution.
Currently, this contribution is essentially uniformly unfavorable, leading to universal rejection.  This might be a real problem, or might be a dumb mistake.
Very experimental.
> Implement additional contribution to acceptance probability

- perses/annihilation/ncmc_switching.py
- perses/rjmc/topology_proposal.py
- perses/tests/test_elimination.py
- perses/tests/test_geometry_engine.py
- perses/tests/test_sampler.py
- perses/tests/test_topology_proposal.py
Changes:
* turned ```proposal_metadata``` and ```current_metadata``` into optional arguments
* removed ```current_positions``` from ```PointMutationEngine.propose()``` -- generating ```np.zeros``` for ```Modeller``` input instead, can later eliminate ```Modeller``` altogether but not currently a priority
* ```chain_id``` is input to ```PointMutationEngine``` constructor
* ```PointMutationEngine._ff``` obtained from ```SystemGenerator```
* added method ```compute_state_key(self, topology)```
* returning ```old_chemical_state_key``` and ```new_chemical_state_key```
> Creating chemical_state_key for PolymerMutationEngines (and other minor fixes)

- perses/rjmc/geometry.py
- perses/tests/test_geometry_engine.py
Fixed a test API and added support for bond constraints. As noted in #50 , the only remaining issue is to determine the `constraint_tolerance` for the reverse logp.
> Adding constraints, fixing a couple tests.

- perses/rjmc/topology_proposal.py
- perses/tests/test_topology_proposal.py
It no longer requires a `receptor_topology`, instead removing the small molecule by the name set in the constructor (default MOL) each time to get the appropriate environment.
> Fix SmallMoleculeProposalEngine

- .travis.yml
- perses/rjmc/topology_proposal.py
Makes sure that the input smiles strings are canonical isomeric smiles in the openeye flavor by taking the input library and converting each to an `OEMol` then to canonical isomeric SMILES.
> Canonicalize input smiles

- perses/annihilation/ncmc_switching.py
- perses/tests/testsystems.py
- perses/tests/utils.py
SMILES strings in all `testsystems` now
* expand all unspecified stereocenters into all possible chiral variant molecules
* convert all molecules to canonical isomeric SMILES so they can be round-tripped to get identical SMILES strings
This is handled through new functions in `perses.tests.utils` that will eventually get moved to `openmoltools`:
* `sanitizeSMILES(molecule_list)` handles the sanitization (in a fast manner that doesn't involve `OEOmega`)
* `enumerate_undefined_stereocenters(molecule)` expands molecules with undefined stereocenters
* `has_undefined_stereocenters(molecule)` returns `True` if `molecule` has undefined stereocenters
Addresses #120
> Sanitize SMILES strings used in testsystems

- perses/rjmc/topology_proposal.py
- perses/samplers/samplers.py
- perses/tests/testsystems.py
@pgrinaway: Try out 
```
python perses/tests/testsystems.pdb
```
and look at the generated `kinase-inhibitors-vacuum-geometry-proposals.pdb`, which writes out the geometry proposals.  Is this just the ring fusion problem?
> Make it easy to write out PDB files for proposed kinase inhibitors

- perses/rjmc/geometry.py
- perses/rjmc/topology_proposal.py
- perses/samplers/samplers.py
- perses/tests/testsystems.py
I've turned on writing of atom-by-atom PDBs for geometry proposals to debug what is going wrong with kinase inhibitors.
It looks like the torsion restraints are not actually biasing the placement of closed rings.  I don't know if there was somehow a reversion somewhere, since this was working before.
> Fix geometry engine torsion biases and MCSS overlap criteria

- perses/rjmc/geometry.py
- perses/tests/test_geometry_engine.py
This PR is done. All it does is assign an "index" of -1 for the atoms that we add to make an `OEMol`. This doesn't impact anything else, but will make it easy for @juliebehr to distinguish these atoms when making an atom map between protein residues.
> New atoms for OEMol purpose get -1 index

- perses/rjmc/topology_proposal.py
- perses/samplers/samplers.py
- perses/tests/test_elimination.py
- perses/tests/test_geometry_engine.py
- perses/tests/test_topology_proposal.py
- perses/tests/testsystems.py
Addresses https://github.com/choderalab/perses/issues/190
The IP part is that I'm pretty sure I've altered the intended behavior of ```test_mutate_from_every_amino_to_every_other``` because I was previous taking advantage of the fact that I didn't actually go back to wildtype before making a new mutation, and now when I try to initiate my little protein with 20 different amino acids to start, it will actually only change 1 away from the wildtype (I think).
> Modify chemical_state_keys from PointMutationEngine

- .travis.yml
- perses/samplers/samplers.py
- perses/tests/test_samplers.py
- perses/tests/testsystems.py
Added the `geometry_engine` constructor argument, and put in the `FFAllAngleGeometryEngine` as the default for all perses test systems.
> Add GeometryEngine as constructor argument to ExpandedEnsembleSampler

- perses/rjmc/geometry.py
This is pretty simple, but is just here to prevent accidental use of the (incomplete) sterics support (there are no exceptions, for instance). I have it raising an exception now, but if that's a bit excessive I can change it back. As long as tests pass on this and we agree it is appropriate for now, I will merge.
> Prevent use of sterics in GeometryEngine

- .travis.yml
- devtools/conda-recipe/meta.yaml
- setup.py
The failures we've suddenly started seeing are all due to:
```
$ source activate _test
could not find environment: _test
```
Suspiciously, `conda build` now gives this error:
```
INFO:/home/travis/miniconda/lib/python2.7/site-packages/conda_build/config.pyc:--keep-old-work flag not specified. Removing source and build files.
```
I've added `--keep-old-work` with the idea that this will restore the ability for us to test from the `_test` environment created by `conda build`.
> Fix travis after change to 'conda build'

- perses/rjmc/geometry.py
- perses/tests/test_geometry_engine.py
This PR fixes three important bugs in the geometry engine:
* The correct growth index was not always being used in the valence `System` because of rounding errors
* Ring-closing torsions were not being added with their appropriate growth index
* Hydrogen atoms were being grown before heavy atoms, causing rings to sometimes not close
> Geometry engine bugfixes

- perses/rjmc/topology_proposal.py
- perses/tests/test_topology_proposal.py
Addressing bug https://github.com/choderalab/perses/issues/244 for cases where `allowed_mutations` have not been specified.  Previously, would have prevented moves back to WT, after a move away from WT has been accepted.  Now, requires every mutation from the previous state to be different.
For instance, if your WT sequence is:
`1MET-2TYR-3ILE-4PHE-5SER` and `max_allowed_mutants = 2`
the first proposal will choose 2 locations at random, and change them to anything other than the WT residues, possibly:
```
locations = [2, 5]
1MET-2GLN-3ILE-4PHE-5LEU
chemical_state_key = 'TYR2GLN-SER5LEU'
```
The next proposal first chooses 2 locations at random, then changes those residues to anything other than what they were previously (therefore allowing a return to WT in the event that the same …
> Correct behavior for always_change

- perses/rjmc/geometry.py
- perses/tests/testsystems.py
This allows `GeometryEngine` to properly handle bond constraints while calculating the `logp_reverse`. We assume that constraints have been satisfied.
> Fix bond constraint reverse logp

- README.md
This just adds a warning notice to the readme for all users who want to play around with `Perses`. I put it in PR form to make sure everyone was ok with it.
> Add warning notice to readme

- perses/rjmc/topology_proposal.py
With `_always_change`, `_propose_mutations()` chooses a location to make a mutation, and is then supposed to make the probability of the chosen residue staying the same = 0.
Previously, an `if` statement gave different behavior if the proposed residue to change was either the WT residue or already mutated.  The `if` statement contained a bug (improperly using `proposed_location` as the residue index, when it is actually the index in the list of `_residues_allowed_to_mutate` if that has been specified), but also was unnecessary, because `original_residue` refers to the residue in the `old_topology`, whether or not that is the WT residue.
> Eliminate KeyError in _propose_mutations

- perses/annihilation/ncmc_switching.py
Hybrid ncmc engine returns different values than the regular one, but previously the special case of 0 ncmc steps was not altered from the parent class.  The expanded ensemble sampler will expect initial positions returned instead of logp_ncmc.
> Fix hybrid ncmc case with 0 steps

- perses/annihilation/relative.py
- perses/samplers/samplers.py
- perses/tests/test_samplers.py
- perses/tests/testsystems.py
This PR features 3 fairly minor changes:
- renaming the scheme which implements `NCMCHybridEngine` from `geometry-ncmc` to the more appropriate `geometry-ncmc-geometry` (change made in `samplers.py` and `test_samplers.py`)
- creating the actual `geometry-ncmc` scheme, which would be the asymmetric jump from a physical old system to an alchemical new system at `lambda=0` -- **raises NotImplementedError** but is there in case it's ever wanted in the future
- changing the storage calls at the end of `ExpandedEnsembleSampler.update_state()` which had previously been outdated for the hybrid scheme; moving as many as possible to outside the `if scheme` loops to eliminate duplicate code (and also to help ensure one scheme wouldn't become outdated again in the future)
Also, corrects a bug in …
> Updates to NCMC Schemes within ExpandedEnsembleSampler

- perses/annihilation/ncmc_switching.py
- perses/tests/benchmark.py
Extracting changes in the `hybrid-tests` branch that are independent to testing hybrid builder; here: refactoring `ncmc_switching.py` to inherit between `NCMCEngine` and `NCMCHybridEngine`
> NCMC refactor -- cherry picking from hybrid-tests

- perses/rjmc/topology_proposal.py
Self-explanatory correction: `atom_map` was getting atoms instead of their indices
> PropaneTestSystem -- addendum

- perses/annihilation/ncmc_switching.py
- perses/annihilation/relative.py
- perses/rjmc/topology_proposal.py
- perses/samplers/thermodynamics.py
- perses/tests/test_geometry_engine.py
- perses/tests/testsystems.py
- perses/tests/utils.py
Bugfixes culled (by hand) from #284:
* SMILES strings are now canonicalized by converting them to OpenMM `Topology` objects and back to SMILES again. Without this, the protonation state of imidzole would end up with a different SMILES strings that wasn't in the original set. This is fixed for all testsystems.
* The proposal engines would silently remove any barostats because `SystemGenerator`had no facility to add these to newly generated systems. I've added a way to specify that `SystemGenerator` should add a barostat, and added this to all testsystems.
* `removeCMMotion` is now disabled by the system generator if not explicitly specified
* `HybridTopologyFactory` would raise a puzzling exception when the number of forces differed between `system1` and `system2` (because of the missing …
> Various bugfixes

- perses/rjmc/topology_proposal.py
There was a bug in the small molecule proposal engine that caused it to
ignore the atom and bond expressions given to it for atom matching. This
commit resolves that bug
> Fix atom map bug in SmallMoleculeProposalEngine

- .travis.yml
@jchodera noticed a flaw with the git-flow model in that travis builds were not triggered, leading to introduction of new errors. This PR would enable travis for all branches except those with `notest` in them. (I don't know at the moment why we'd want that, but it might be useful at some point). We'd then be able to check the status of all branches on the nice travis dashboard, while keeping the clean development model of git-flow.
> Allow travis builds on all branches

- perses/rjmc/geometry.py
Two fixes:
* Choose eligible atoms based on torsions that are available (atoms234 have positions)*
* Randomize order of atoms proposed within an "eligible group" and account for this in the logp
*atom1 is by definition always the new atom of interest.
> Quick eligible atoms fix

- perses/storage/storage.py
- perses/tests/test_elimination.py
- perses/tests/test_storage.py
This is a small PR with a few storage fixes:
* `get_object` had the variable name hardcoded, which prevented it from being used. This is fixed, but I had to add two extra parameters to `get_object`: `envname` and `modname`. 
* The test happened to use the exact same name as the hardcoded variable, so it was passing. I changed it to use some names we might encounter in simulation (though maybe even just a random string would suffice)
I debated for a bit about how to do this exactly in the spirit of the API, but I decided on the quick patch now so that we could keep going. I'm happy to take a look at this again later.
> Storage fixes

- devtools/travis-ci/install.sh
This pins `conda-build` to 2.1.5 until https://github.com/conda/conda-build/issues/1825 is resolved.
> Fix travis builds

- perses/annihilation/ncmc_switching.py
This changes the unused `ke` to `kinetic`. Let me know if something is amiss. Should resolve #323
> Fix name of variable error in NCMCIntegrator

- perses/annihilation/new_relative.py
This PR does two things:
* Fixes a bug where the wrong range is used for looping through the bond force and angle force.
* Allows (but does not expect by default) specification of the alchemical functions in the hybrid. The advantage of this is that we can get openmm to calculate dU/dlambda easily. This would presumably also allow for alchemical functions to be defined using the OpenMM spline classes as well, which are accessible from the force side but not the integrator side.
> Fix bug + add feature

- perses/annihilation/ncmc_switching.py
- perses/annihilation/new_relative.py
- perses/annihilation/relative.py
- perses/distributed/relative_setup.py
- perses/samplers/samplers.py
- perses/samplers/thermodynamics.py
- perses/tests/benchmark.py
- perses/tests/test_elimination.py
- perses/tests/test_geometry_engine.py
- perses/tests/test_ncmc_integrator.py
- perses/tests/test_topology_proposal.py
- perses/tests/testsystems.py
- perses/tests/utils.py
Fixes #359: Use `kB` and `ONE_4PI_EPS0` from `openmmtools.constants`.
> Use constants from openmmtools

- perses/distributed/relative_setup.py
The `relative_setup.py` file defined `temperature`, `kT`, and `beta` at the top-level of the file, and used this top-level `beta` but a function argument `temperature` (could be different) potentially leading to contradictory temperatures. This eliminates top-level temperature definitions.
Note that I can't find anywhere the function `generate_vacuum_hybrid_topology` is either used or tested in `perses`. Should this be deleted?
> Remove temperature defined at top-level of application file

- perses/distributed/feptasks.py
- perses/distributed/relative_setup.py
Fixes #368.
Since #1870, the development version of OpenMM has `Context.getIntegrator()` return the correct Python subclass, so the `restore_properties()` workaround should no longer be needed (and would also interfere with the ability to call `integrator.reset()`).
We may also have to update `openmmtools.ContextCache()` to streamline the `RestorableIntegrator` scheme, but this will only work with OpenMM 7.2 and later, so we should hold off on that if we can.
Docstrings have also been clarified.
> Reset NCMC statistics before nonequilibrium switching

- perses/annihilation/new_relative.py
This problem did not affect actual system creation, but resulted in the
MDTraj topology that was generated being unable to be deepcopied. To
resolve it, for each unique new atom that gets added, we find the
corresponding residue and extract it from the hybrid, then use that to
add the new atom.
> Fix topology creation to use the residue from the hybrid topology

- perses/annihilation/new_relative.py
This PR updates the constraint check to use the system XMLs and lxml; this is much faster (on the order of 15sec instead of 15min) and allows us to re-introduce the constraint check. This should resolve #363 by raising an exception if a constraint is changing.
> Faster constraint check

- perses/annihilation/new_relative.py
- perses/distributed/feptasks.py
- perses/distributed/relative_setup.py
In this PR, I'm switching the `feptasks.py` tasklets to use the MCMove framework. This will also involve some substantial changes to `relative_setup.py` in order to accommodate the new (and cleaner, I think) API.
> Switch to using MCMove framework in feptasks.py

- devtools/conda-recipe/meta.yaml
- perses/rjmc/topology_proposal.py
- perses/tests/test_topology_proposal.py
- setup.py
Addresses #438 
This took an hour longer than expected to implement because my first idea turned out to be too simplistic to catch the naphthalene -> benzene issue, and the second idea used the [OpenEye tools](https://docs.eyesopen.com/toolkits/python/oechemtk/ring.html#section-ring-cyclic-membership) which aren't able to enumerate all cycles. Instead, I was forced to resort to using [NetworkX to enumerate a cycle basis](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.cycles.cycle_basis.html?highlight=cycle_basis#networkx.algorithms.cycles.cycle_basis) that should catch all cases we care about.
I've added a corresponding naphthalene -> benzene test to make sure we allow this transformation when `allow_ring_breaking=True` and disallow this …
> Check to make sure atom mapping preserves rings

- perses/dispersed/relative_setup.py
The integrator being used for nonequilibrium switching had defaulted to a metropolized VVVR, which is not what we want for several reasons:
* It doesn't match the equilibrium simulation
* It's extremely slow (both in terms of runtime and correlation time)
This PR changes the splitting string to `VROHORV`, which is BAOAB with the hamiltonian update in the middle.
> Change integrator for NE switching to use BAOAB

- perses/dispersed/feptasks.py
- perses/dispersed/relative_setup.py
This PR fixes a large bug we identified last week where multiple calls to [run](https://github.com/choderalab/perses/blob/master/perses/dispersed/relative_setup.py#L512) in `relative_setup.py` leading to integrator errors in [run_protocol](https://github.com/choderalab/perses/blob/master/perses/dispersed/feptasks.py#L144) where `ne_mc_move.apply(thermodynamic_state, sampler_state)` would return near zero work values. Upon debugging this step we found that neither `lambda` nor `step` in the integrator was increasing every time apply was called (over 100 iterations), AFTER the initial [run](https://github.com/choderalab/perses/blob/master/perses/dispersed/relative_setup.py#L512) command. I have validated that this PR fixes this issue on my local linux and lilac setup. This issue was …
> Fixing shadow_work and dask gather bug.

- perses/dispersed/relative_setup.py
There was a mistake that remained from the previous PR. I eliminated the superfluous forcefield object, but was apparently using it elsewhere. It wasn't caught by the test because the solvated setup is too long to run on travis.
> Remove use of no-longer-existing self._forcefield

- perses/annihilation/new_relative.py
This PR modifies the code by adding 3 optional constructor arguments:
* `softcore_alpha` and `softcore_beta` are now exposed as constructor parameters.
* We allow multiple softcore schemes:
* `default` (the default): unique atoms become more softcore as they approach their endpoints. Core atoms become fully softcore in the middle of the protocol, and are not softcore at the endpoints.
* `amber`: replicates the technique shown in the AMBER manual. Identical to `default`, except that the core is never softcore.
* `classic`: the old scheme. All alchemical atoms become 0.25*softcore at the middle of the protocol, and are not softcore at the endpoints.
> Modify softcore options

- perses/annihilation/new_relative.py
- perses/dispersed/relative_setup.py
Instead of switching sigma to 1.0 when it is being turned off, this switches sigma to machine epsilon. It can't be switched to zero, otherwise OpenMM will complain that the number of exceptions is changing. When it is switched to 1.0, it has no effect at the endpoint as long as epsilon is zero; however, it creates a very strange protocol for intermediate states that could be inefficient.
I need to evaluate this to see if that is what happens.
> Improve alchemical path for atoms being created/destroyed

- devtools/conda-recipe/meta.yaml
- examples/cdk2-example/cdk2_setup.yaml
- perses/annihilation/new_relative.py
- perses/dispersed/relative_setup.py
- perses/rjmc/geometry.py
- perses/rjmc/topology_proposal.py
- perses/tests/test_hybrid_builder.py
- scripts/setup_relative_calculation.py
@pgrinaway : I think I've made all the changes necessary to use the new ['offset' OpenMM feature](https://github.com/pandegroup/openmm/pull/2105) for near-exact nonbonded electrostatics, but I can't figure out which overlap tests I can run to test that this is actually working. Can you help?
At first, I thought [`test_simple_overlap()`](https://github.com/choderalab/perses/blob/master/perses/tests/test_hybrid_builder.py#L307-L318) may work, but it appears to use several broken functions. Is there another test that is supposed to work for checking overlap with the physical endpoints?
The `offset` feature is being built as `openmm==7.3.0` right now.
This PR would replace #469 since we would no longer need that solution.
> [WIP] Modifications to use new 'offset' OpenMM feature for nonbonded electrostatics

- perses/data/protein.ff14SB.protonated-termini.xml
- perses/data/protein.ff14SB.xml
- scripts/README.md
- scripts/generate-protonated-termini.py
Maestro files were previously difficult to deal with if the C-terminal carbon was protonated with `HXT`.
This PR adds a script in `scripts/` to generate new ffxml file derivatives for amino acids with protonated C-termini. I've added the converted file for `protein.ff14SB.xml` to `perses/data/protein.ff14SB.protonated-termini.xml`.
Example usage:
```python
from simtk.openmm import app
filename = 'Inputs_for_FEP/MCL1_protein.pdb'
print('Reading {}...'.format(filename))
pdb = app.PDBFile(filename)
print('Reading forcefield...')
forcefield = app.ForceField('protein.ff14SB.xml', 'protein.ff14SB.protonated-termini.xml')
print('Creating system...')
system = forcefield.createSystem(pdb.topology)
print('Done.')
```
> Add ffxml file with C-terminal protonated termini

- perses/rjmc/geometry.py
- perses/tests/test_geometry_engine.py
- perses/tests/test_hybrid_builder.py
This PR replaces the flawed `ProposalOrderTools`---which frequently encountered cases where it could not identify topological torsions---with a NetworkX-based scheme from @pgrinaway (rescued from another branch).
> Replace flawed ProposalOrderTools with NetworkXProposalOrder

- perses/rjmc/geometry.py
This PR addresses `NetworkXProposalOrder: proposal_order is empty` errors
> Fix `NetworkXProposalOrder: proposal_order is empty` errors

- .travis.yml
- README.md
- devtools/conda-recipe/meta.yaml
- perses/tests/test_coordinate_numba.py
This PR updates travis tests to include python 3.6 and python 3.7 with OpenMM 7.3.1, as well as allowed failures testing OpenMM beta and dev versions.
I've also relaxed the tolerance for a stochastically failing numba test, and made it report more information when it fails.
> Update travis tests to include allowed failures against OpenMM beta and dev versions

- .travis.yml
This PR adds a travis branch (under `allowed_failures:`) that also tests the [`conda-forge` test builds](https://anaconda.org/conda-forge/openmm/files).
> Add travis branch to test openmm conda-forge testing builds

- perses/annihilation/relative.py
- perses/app/setup_relative_calculation.py
- perses/samplers/multistate.py
This PR removes any use of the FIREMinimizationIntegrator, and instead uses functions that rely on openmm.LocalEnergyMinimizer instead, which has been more robust - particularly with hybrid systems.
> [MRG] Fix minimizers

- perses/annihilation/relative.py
- perses/app/relative_setup.py
- perses/rjmc/topology_proposal.py
Addresses #592
Core atoms are being mistakenly labelled as environment when:
- there are no unique new or old atoms
- the topology proposal is being generated from a higher order phase in the setup.
The TopologyProposal is instantiated using parameters gleaned from setting up the higher order (i.e. complex > solvent > vacuum) and the new and old residue names aren't set, so default to `None`
i.e. this bug doesn't arise if you _just_ run a vacuum leg, only if a solvent leg is set up and we try 'extract' the vacuum leg from that.
The defaults in TopologyProposal could instead be changed to 'MOL'
Adding an assert that the number of cores must be at least 3
> [WIP] fixing bug with no unique

- perses/app/setup_relative_calculation.py
- perses/samplers/multistate.py
Instead of expanding cutoffs, it seems simpler to just use LJPME and a tighter PME tolerance.
In this implementation, we
- move all alchemical atom LJ parameters from CustomNonbondedForce back to NonbondedForce
- delete CustomNonbondedForce (since it is no longer needed)
- set PME tolerance to 1e-5
- enable LJPME to handle long-range dispersion correction in physically reasonable manner
I'm not sure which test(s) to run, so this is implemented as best I can without running any tests, and may still need some debugging.
See the warning that the platform precision may not actually be set to `mixed` using the scheme you had been using:
```python
context, _ = context_cache.get_context(compound_thermodynamic_state)
platform = context.getPlatform()
logger.info('Setting the platform precision to …
```
> Use LJPME for endstate corrections instead of expanded cutoff

- perses/app/setup_relative_calculation.py
- perses/samplers/multistate.py
- perses/tests/testsystems.py
- perses/utils/openeye.py
This adds an optional argument called `n_samplers` which defines the number of sampler states to run with. If `n_samplers != n_states` it will pick approximately equally spaced sampler states from the list.
The default for n_samplers is to equal n_states, but possibly we would want the defaults to be:
REPEX n_samplers = n_states
SAMS n_samplers = 1
?
> Changing Hybrid{sams|repex}Sampler to accept variable number of sampler states

- perses/analysis/load_simulations.py
- perses/app/relative_setup.py
- perses/app/setup_relative_calculation.py
- perses/dispersed/utils.py
- perses/rjmc/geometry.py
- perses/rjmc/topology_proposal.py
- perses/utils/openeye.py
This PR
** I am opening Issue #656 to try understand what types of things count as ring breaking, and how we can juggle all different sorts of things simultaneously
*** This means that `constraint_tolerance=1e-06` has been taken out
**** I can just try run this on one of complex/solvent to get a speed up
> Updating small molecule pipeline to fit into the new protein-mutation stuff

- perses/analysis/fah_analysis.py
- perses/analysis/resample.py
This PR pulls out some of the common bootstrapping code into a new submodule, `perses.anaylsis.resample`.
Also includes various fixes:
- Typo in standard error of sum formula: 0860cd5
> Add library functions for bootstrapping

- perses/app/fah_generator.py
- Only generate necessary directories (complex, solvent, apo, vacuum) based on yaml file
- ~Allow removal of HBond constraints~
> Fix Fah generator to only generate yaml-specified directories

- .github/workflows/CI.yaml
remove redundancy in CI.yaml caused by merging
-push
....
was accidentally int the CI.yaml file twice, presumably due to a merge issue. This simply removes the duplicate
> Fixing CI run

- perses/data/barstar-mutation/mutant.yaml
Update example yaml file for running protein mutations using `fah_generator.py`
> Update protein mutation fah yaml

- perses/utils/openeye.py
Removes an extra `OEAddExplicitHydrogens` statement in `createOEMolFromSDF` that isn't needed
> remove extra OEAddExplicitHydrogens

- perses/app/relative_point_mutation_setup.py
This PR adapts the input of `PointMutationExecutor` to allow for a list of oemol objects to be used instead. Both @schallerdavid and I were having difficulty parsing ligand `.sdf` [files](https://github.com/openkinome/study-ntrk-resistance/tree/perses_sims/notebooks/kinoml_modeling/data) containing a nitrogen that was perceived as needing to be tetrahedral at [this line](https://github.com/choderalab/perses/blob/master/perses/utils/openeye.py#L366) in `perses.utils.openeye`. This PR allows the user to bypass internal oemol preparation. 
Changed:
- `PointMutationExecutor` now takes inputs: `.sdf`, `.pdb`, `[oemol]`.
- `ligand_file` renamed to `ligand_input` to be more general.
An example script of how to prepare the `[oemol]` object is below, input names changed from my use case:
```python …
```
> Use a list of oemols for PointMutationExecutor input instead of files

- .github/workflows/CI.yaml
Adressing two things:
* `add-path` and `set-env` commands are deprecated and will be disabled on November 16th. More information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
* I merged the new conda forge packages for OpenMM so they use the `test` label (and not `testing`) following what CF is doing for `cudatoolkit`. This will allow us to test the latest builds!
> Setup miniconda v2 & use new CF OpenMM

- .github/workflows/CI.yaml
- devtools/conda-envs/test_env.yaml
- perses/app/relative_setup.py
- perses/dispersed/utils.py
- perses/rjmc/geometry.py
- perses/samplers/samplers.py
As a first pass in improving our testing, we are going to switch to using [`pytest`](https://docs.pytest.org/en/stable/) to run tests. Because of the [compatibility between `pytest` and `nose`](https://docs.pytest.org/en/stable/nose.html) we shouldn't need to do anything to the old tests, but we should start writing new tests using `pytest` features.
> Switch to pytest runner

- perses/app/relative_point_mutation_setup.py
Currently, the `temperature` is defaulted at 300 K, but it should be 298 K (as the default temperature for integrators in `openmmtools` is set to 298 K and 298 K is closer to 25 celsius).
> Change default temp in protein mutation setup pipeline

- perses/app/relative_point_mutation_setup.py
This is directly related to #673. 
In this PR I've added an option to set `allow_undefined_stereo` when creating an `OEMol` object using `createOEMolFromSDF` in `relative_point_mutation_setup.py`.
@schallerdavid and I are working with sets of ligands that contain undefined stereocenters after preparation with OpenEye (this has been reported to them and they are working on a fix). Until this is solved (or we move to `openforcefield`, as discussed in #657) we need an option to relax the requirement that all stereocenters need to be defined.
> add allow_undefined_stereo option for SDF files with undefined stereocenters

- devtools/conda-recipe/meta.yaml
- perses/app/fah_generator.py
- perses/app/relative_setup.py
Fixes #811: Restores default timesteps to 4 fs, constrained bonds to hydrogen
Note that the pathological constraint issue was fixed in openMM 7.5.0
> Fix #811: Restore default timesteps to 4 fs, constrained bonds to hydrogen

- perses/app/setup_relative_calculation.py
Write out YAML file after parsing.
In order to improve reproducibility and quickly see which options were used in the simulation, it would be nice to be able to inspect the YAML that has all the options set as parsed.
Resolves #817 
Tested on GHA and locally manually.
```
Write out YAML file after all options are parsed and set. Saved as YAML original file name + date + time. 
```
> Write out YAML file after parsing

- perses/annihilation/relative.py
- perses/app/fah_generator.py
This allow the serialization of new and old positions in pdb files as well as atom mappings in numpy object file, when creating hybrid topologies. 
Resolves #752 
Tested using [minimal-neq-sprint.tar.gz](https://github.com/choderalab/perses/files/6948343/minimal-neq-sprint.tar.gz) by running `python 05-prepare-single-transformation.py 0`
Addresses (issue #752 ) by storing positions and maps for new and old molecules when creating a hybrid topology.
```
```
> Store new and old positions and maps

- perses/app/relative_setup.py
This change makes sure input ligand file exists when running simulations with the CLI. Avoiding freezing.
Resolves #836 
Tested manually so far.
```
Avoid freeze if ligand file is not found or does not exist when using CLI.
```
> CLI - Making sure input ligand file exists

- perses/app/relative_point_mutation_setup.py
- perses/tests/test_relative_point_mutation_setup.py
The default behavior of `PointMutationExecutor` in Perses 0.9.2 leads to a `NameError` since `forward_htf` is not defined. This PR aims to fix the endstate validation handling.
The defaults in `PointMutationExecutor` lead to a `NameError`.
Resolves #865 
I tested the changes with an ABL1:dasatinib system ([protein](https://github.com/openkinome/study-abl-resistance/blob/update_modeling/data/tki_complexes/kinoml_OEKLIFSKinaseHybridDockingFeaturizer_ABL1_2gqg_chainA_altlocA_dasatinib_protein.pdb), [ligand](https://github.com/openkinome/study-abl-resistance/blob/update_modeling/data/tki_complexes/kinoml_OEKLIFSKinaseHybridDockingFeaturizer_ABL1_2gqg_chainA_altlocA_dasatinib_ligand.sdf)):
```
solvent_delivery = PointMutationExecutor(
protein_path, 
'1', # First and only protein chain …
```
> Fix endstate validation handling in PointMutationExecutor

- .github/workflows/CI.yaml
- devtools/conda-recipe/meta.yaml
Removed forks when installing openmm nightly 
Now that parmed has made a new release to support the openmm name change + we just cut (will be on conda-forge soon) a new openmoltools release, these CI hacks are no longer needed.
Resolves #798 
Tested on CI
```
CI no longer requires forks for openmm namespace changes.  
```
> Remove hacks now that upstream has updated packages

- .github/workflows/CI.yaml
This PR installs openeye toolkit with the `beta` label https://anaconda.org/OpenEye/OpenEye-toolkits/files
Instead of expanding the matrix, I opted to do this as part of the openmm nightly check, since it isn't required to pass + didn't want to eat up too much CI time. 
We want to be able to check if any changes to the toolkit cause our tests to fail. We also want to be able to report bugs back to openeye.
Resolves #883 
```
```
> use beta of openeye toolkit

- perses/tests/test_topology_proposal.py
This PR piggy backs off of https://github.com/choderalab/perses/pull/860, where I forgot to allow `demap_CBs` to be passed to `generate_dipeptide_top_pos_sys`.
This is necessary because to enable generating protein mutation test systems with demapped CBs.
```
```
> Allow `generate_dipeptide_top_pos_sys` to accept `demap_CBs`

- perses/tests/test_geometry_engine.py
> Remove unused argument 'implicitSolvent' from SystemGenerator in tests

- .github/workflows/CI.yaml
- .github/workflows/self-hosted-gpu-test.yml
Quick change to ignore issues we hare having with codecov while we wait to hear from them:
https://community.codecov.com/t/too-many-uploads-to-this-commit-code-invalid/3384
> Disable CI failure if codecov fails 

- perses/rjmc/topology_proposal.py
This PR makes sure that when a source topology is being copied to a destination topology, the source topology's box vectors are copied to the destination topology.
OpenMM only writes out box vectors to DCD files if the `topology.getPeriodicBoxVectors()` is not None: https://github.com/openmm/openmm/issues/3418
I ran a simulation and the box vectors were not saved because `htf._topology_proposal.old_topology` does not have box vectors. This PR addresses the problem by adding a line that copies the box vectors from the source to destination topology in `append_topology()`. It removes the line in `_propose()` that does this for the new topology only.
```
```
> Fix box vector handling in topology proposal

- perses/annihilation/relative.py
Takes the average of old and new system masses for mapped (environment/core) atoms.
Currently, the `HybridTopologyFactory` adds all environment/core/unique old atoms to the hybrid system using the mass of the particle in the old system. It then adds unique new atoms using the mass of the particle in the new system.
To improve stability, we want to average the old and new system masses for any mapped atom (environment/core atoms). 
Resolves #910
```
```
> Fix atom masses in vanilla HybridTopologyFactory

- perses/rjmc/topology_proposal.py
Currently, we choose a water at least X nm from protein to change into an ion. If there are glycan residues, the current implementation is incorrect, as a water may be chosen near a glycan, which we don't want. 
This PR changes the selection string from `protein` to `not water and not resn NA and not resn CL and not resn ZN`. The ions in the selection string may be supplied to the method as a list of strings.
Resolves #???
```
```
> Fix water selection for counterion

- .github/workflows/CI.yaml
- .github/workflows/self-hosted-gpu-test.yml
We had an issue where codecov would fail to upload reports when we uploaded too many with the same commit hash, this will prevent reports being uploaded when we don't expect anything to change.
> Stop uploading coverage reports on nightly CI runs

- perses/app/setup_relative_calculation.py
Making perses use the new way of specifying context cache from `openmmtools`. This means setting up the simulations to use the energy and sampler context caches, respectively.
* Avoid cycling issue by specifying context caches. 
* Fixes simulation cooling down on resume.
* Minimizes systems before equilibration and production, for repex and sams.
Resolves #902 
Resolves #904 
Resolves #936 
Resolves #900 
```
* Using new streamlined way of dealing with context caches from openmmtools
* Avoid cool down of simulation on resume.
```
> Use energy and sampler context caches in simulations

- perses/analysis/visualization.py
- perses/tests/test_visualization.py
Make fixes to the visualization module related to:
- Pymol frames are 1-indexed, but the module had been assuming it was 0-indexed
- Bug: `self._unique_old/new` should be `self._unique_old/new_selection`
- Renaming an object after loading isn't working, so instead, just load the objects as `old` and `new` directly
- Allow color of old residue to be different from the color of the new residue
- Change background protein transparency
- Remove "hide spheres" when we are using stick representation (shouldn't be necessary)
- Do not allow stick/sphere transparencies to fade to transparency 1.0 (completely transparent) -- make the max transparency 0.7, as there are weird visual artifacts when it is 1.0 (the stick/sphere looks white)
- Clarifications to comments/docstrings
Resolves #???
```
```
> Fixes to visualization module

- perses/app/relative_point_mutation_setup.py
- perses/tests/test_relative_point_mutation_setup.py
Allow the PointMutationExecutor to accept solvated PDBs (previously, it only accepted solute PDBs)
Resolves #???
```
```
> Enable PointMutationExecutor input of solvated pdbs

- perses/dispersed/feptasks.py
- perses/dispersed/smc.py
- perses/dispersed/utils.py
- perses/samplers/multistate.py
- perses/samplers/samplers.py
- perses/tests/test_relative.py
We are now avoiding changing the global context cache behavior when importing/using modules.
Resolves #968
Tested manually with snippet found in #968 
```
Global context cache behavior is now unchanged when importing modules.
```
> Avoid changing global context cache behavior on modules imports

- perses/tests/test_relative.py
`flattenedHybridTopologyFactory_energies` was not passing for transformations involving ring amino acids because `validate_energy_bookkeeping` was always set to `True` in the function. It should only be set to `True` if it doesn't involve the transformation does not involve a ring amino acid.
Resolves #???
```
```
> Fix endstate energy validation test for flattened htfs

- benchmarks/benchmark_analysis.py
Currently, the DeltaG calculated vs experiment comparison plots subtract the mean from both axes, leading to nonsensical experimental axes:
This PR adds back the experimental mean free energy to both axes so that the experimental range is correct:
cc: https://github.com/openforcefield/openff-arsenic/issues/42
Resolves what was originally suspected to be an issue with `openff-arsenic` but was just an incorrect usage:
https://github.com/openforcefield/openff-arsenic/issues/42
The attached plot has been generated.
```
Benchmarking now produces a calculated versus experimental DeltaG plot that correctly centers both axes on the mean experimental binding free energy.
```
> Benchmark DeltaG plots now shift data to experimental DeltaG mean.

- benchmarks/benchmark_analysis.py
- benchmarks/run_benchmarks.py
Changing the url strings for benchmarks.
Scripts were failing because the upstream branch was renamed to `main`.
Local and HPC system runs of benchmarks
> Following upstream change in main branch name.

- perses/tests/test_resume.py
This PR closes reporter/storage files in tests and handles better temporary directory on them.
New `openmmtools` was making tests to fail with fatal errors apparently due to how we were using `netCDF`. https://github.com/choderalab/perses/runs/6250638087?check_suite_focus=true#step:9:160
Resolves #???
Tested locally.
```
```
> Closing reporter in resume tests

- perses/app/relative_point_mutation_setup.py
- perses/tests/test_GPU.py
Fix issue with GPU tests where we didn't handle solvated topologies correctly.
See https://github.com/choderalab/perses/issues/975
Resolves 975
@ijpulidos can you test this locally on a GPU? Right now my laptop graphics drivers are borked 
```
```
> remove dead lines in test + keep topology in openmm if we can

- perses/app/relative_point_mutation_setup.py
- perses/tests/test_resume.py
Fixes typo that causes the test to be run in solvent instead of vacuum.
Resolves #990 
```
```
> Fix typo in test_resume.py

- perses/annihilation/relative.py
- perses/annihilation/rest.py
- Renames second `CustomBondForce` in `HybridTopologyFactory` system to `CustomBondForce_exceptions`
- Updates docstring in `HybridTopologyFactory` to contain the list of forces present in the hybrid system
- Fixes docstring for RESTTopologyFactory to accurately reflect the forces in the system 
This change is necessary because https://github.com/choderalab/perses/pull/1007 changes `compute_potential_components()` to use a dictionary where the keys are force names and values are energies.
```
```
> Rename second CustomBondForce in HybridTopologyFactory system and update docstrings

- docs/changelog.rst
- examples/protein-ligand/cli/protein-ligand.yaml
- perses/app/setup_relative_calculation.py
This exposes the `unsampled_endstates` boolean option in the input YAML file for enabling/disabling the creation of unsampled endstates as a long-range steric correction.
Resolves #1033 
Tested locally with protein-ligand cli example. Output of matrix as follows, for `n_states=3`. Dimensions of `3x3` vs `5x5` (Format is not great, sorry).
| `unsampled_endstates:False`  | `unsampled_endstates:True` |
| ------------- | ------------- |
| Deltaf_ij:<br>   0.000  20.018  -3.468<br> -20.018   0.000 -23.485<br> 3.468  23.485   0.000 | Deltaf_ij:<br>   0.000   7.158  21.007  -4.126  -9.088<br> -7.158   0.000  13.848 -11.284 -16.247<br> -21.007 -13.848   0.000 -25.133 -30.095<br>   4.126  11.284  25.133   0.000  -4.962<br>   9.088  16.247  30.095   4.962   0.000 |
```
``unsampled_endstates`` …
```
> unsampled endstates long range correction as an input yaml option

- perses/dispersed/utils.py
- perses/tests/test_relative.py
- perses/tests/utils.py
This PR fixes `create_endstates_from_real_systems()`, which was not creating the unsampled endstates properly. The global parameters in the valence forces (of the unsampled endstate systems generated by `create_endstates_from_real_systems()`) were not being set according to the appropriate endstate. They were always defaulting to the lambda = 0 endstate, meaning that the unsampled endstate at lambda = 1 had a hybrid system with valence terms set for the lambda = 0 endstate. I've introduced a fix that sets the default values for global parameters in the valence forces according to the right endstate. The fix is based on what is done in `create_endstates()` [here](https://github.com/choderalab/perses/blob/d0bec4d822592e06679036aa6345fd2a3a20102f/perses/dispersed/utils.py#L501-L506). 
This …
> Fix create_endstates_from_real_systems

- perses/annihilation/relative.py
- perses/app/relative_point_mutation_setup.py
- perses/app/setup_relative_calculation.py
This PR addresses the following problem: 
The `RESTCapableHybridTopologyFactory` is not performing lifting to the 4th dimension correctly in vacuum. We are maximally lifting to 100 nm, which is much too large. The maximal lifting distance is currently defined by `w_scale * r_cutoff`. For vacuum, we set `r_cutoff` to be 100 nm, which is the distance we want to use when calling `CustomNonbondedForce.setCutoffDistance()`, but we do not want the maximal lifting distance to be that large, therefore, we need to remove the dependence of the maximal lifting distance on `r_cutoff`. 
In fact, we actually don't need the maximal lifting distance to depend on 2 parameters, we can use just 1 parameter, which I'll call `w_lifting`, that defines the maximal lifting distance in nanometers.
This PR does …
> Fix cutoff and lifting parameters in `RESTCapableHybridTopologyFactory`

- perses/app/setup_relative_calculation.py
- perses/data/Tyk2_ligands_example/tyk2_0_3.yaml
- perses/tests/test_relative_setup.py
Adds timestamp and ligands names (old and new) metadata to the generated perses yaml file.
Wrote a new function that encapsulates the generation of the parsed YAML file and adds the mentioned metadata.
Resolves #998 
Created automated unit test for yaml generation in `test_relative_setup.py`. Also tested locally with running the `examples/protein-ligand/cli` example.
```
Perses output yaml file now adds timestamp and ligands names information (for old and new ligands).
```
> Add timestamp and ligands name to output parsed yaml file

- perses/app/relative_setup.py
- perses/tests/test_relative_setup.py
This PR fixes a bug that prevents the user from choosing the padding size (for adding solvent) when the phase is solvent. 
Note: I found this when I was trying to write the small molecule repex internal consistency tests.
Currently the code always uses a 9 angstrom padding whenever the phase is solvent. I removed the code that does this.
Added `tests/test_relative_setup.py::test_relative_setup_solvent_padding`
```
Fix bug in RelativeFEPSetup that prevents user from controlling the padding when solvating for solvent phase calculations. 
```
> Fix RelativeFEPSetup bug preventing user from controlling the padding in solvent phase

- perses/app/setup_relative_calculation.py
Allows users to specify an override like `--override  foo:bar:baz` to be split into `foo` and `bar:baz` instead of `foo` `bar` `baz` which would break our parser. Common use case is to have a url as a key, ie `some_path:http://s3.aws.com`
Resolves #1060 
Tested locally.
```
Fixes bug where if a `:` was in a key, we could not override the arguement in our perses-cli. 
```
> only split after first colon when doing an override

- perses/tests/test_analysis.py
- perses/tests/test_fah.py
- perses/tests/test_geometry_engine.py
- perses/tests/test_parallel.py
- perses/tests/test_relative.py
- perses/tests/test_relative_setup.py
- perses/tests/test_samplers.py
- perses/tests/test_smc.py
- perses/tests/test_storage.py
- perses/tests/test_utils.py
- perses/tests/test_visualization.py
Skips broken tests.
Instead of using the envar `GITHUB_ACTIONS` to conditionally skip these tests, we should just skip them because they are broken. This makes it easier to run tests locally.
Resolves #???
Locally and on CI
No entry needed.
```
```
> skip broken tests

- perses/rjmc/geometry.py
- perses/tests/utils.py
By default the `CUDA` platform was hardcoded in the geometry engine. Generating contexts that were not handled correctly. This PR is aimed towards making `CPU` to be the default platform for the geometry engine and cleans explicitly created contexts for a better memory management.
Resolves #1085 
```
``CUDA`` platform was hardcoded in geometry engine, generating performance issues by not clearing openmm contexts correctly. Fixed by defaulting to using the faster ``CPU`` platform (for the geometry engine) and explicitly deleting context variables after they are used.
```
> Cleaning up platform and context usage in geometry engine

- perses/app/relative_point_mutation_setup.py
- perses/app/setup_relative_calculation.py
- perses/dispersed/utils.py
- perses/rjmc/geometry.py
- perses/tests/test_relative.py
- perses/tests/test_rest.py
- perses/tests/test_topology_proposal.py
- perses/tests/utils.py
These changes make the `CPU` platform to be the default platform for the geometry engine.
While working on these changes, it was noted that some of the utility functions lived in the wrong module under `perses.tests.utils`, they were moved to a "better" module in `perses.dispersed.utils`, since we should reserve the `perses.tests.utils` module for things that are only required in our tests.
Backward compatibility is achieved by having variables in `perses.tests.utils` to point to the new `perses.dispersed.utils` functions as needed. This is to avoid breaking workflows of users calling these functions directly from `perses.tests.utils`,
It was noted in https://github.com/choderalab/perses/pull/1091#discussion_r951883596 that we didn't want to change the default platform in general for that …
> Geometry engine platform usage cleanup

- perses/tests/test_resume.py
Fix issue with test using old CLI
Resolves #1150 
tested locally and on lilac, this test is skipped on CI
```
```
> resolves issue #1150

- .github/workflows/CI.yaml
- devtools/conda-envs/test_env.yaml
- perses/tests/test_examples.py
From #1145 our examples directory was populated with many scripts that are not necessarily ready-to-run examples.
These changes avoid trying to run these as part of our CI, solving errors on running tests.
Tested locally running `test_examples.py` tests.
> Avoid testing non-examples in CI

- perses/utils/data.py
There was a bug in the logic where if we saved a file with a `.gz` extension, we would save the file compressed, then overwrite the file with an uncompressed version.
Since this commit: 1145a7405f4beb0de10ab80aa80f6e01aa1a8794 we have not actually been compressing our xml files.
Resolves #1157 
Tested locally. I could be convinced to write a test, but with the refactoring coming up, I think will prefer to use a different method for this. 
```
Resolves #1157 objects serialized with utils.data.serialize now will be compressed with bzip2 or gzip depending on file name (.gz and .bz2, respectively)
```
> fix issue with logic, add debug statements

- .github/workflows/CI.yaml
- devtools/conda-envs/test_env.yaml
To save some compute time/carbon, we are only going to test `dev` with the latest python version.
Resolves #???
```
```
> only run dev with newest python version

- perses/tests/test_repex.py
Since openmmtools 0.23 the online analysis interval and the checkpoint interval are now correlated. See https://github.com/choderalab/openmmtools/releases/tag/0.23.0 for more info.
Work with latest openmmtools changes
Tested locally, will test with self-hosted GPU CI when merged.
```
```
> Using default online analysis interval in GPU repex tests

- examples/new-cli/template.yaml
- perses/app/relative_setup.py
- perses/app/setup_relative_calculation.py
- perses/tests/test_cli.py
These changes allow the specification of the solvent model through the input YAML file for the small molecule pipeline in perses. This is intended to be used via the perses cli.
Some users have expressed the desire to use different solvent models for perses simulations.
Resolves #1192 
```
Users can now specify solvent model for simulations using the ``solvent_model`` field in the input YAML file.
```
> Allow specifying solvent model in input YAML file

- docs/changelog.rst
> release notes for 0.10.2

- .github/workflows/CI.yaml
- devtools/conda-envs/test_env.yaml
* Allow codecov to fail without making our CI tests error out. This is desirable because codecov availability can be flaky, so we don't want to depend on it for our CI tests to pass.
* We don't need to pass `openmmtools >=0.23` as extra specs. Test environment file updated accordingly.
> CI miscellaneous fixes

- perses/app/relative_setup.py
- perses/tests/test_relative_setup.py
These changes remove an unnecessary call to `RelativeFEPSetup._setup_complex_phase` method, fixing the support for spectator molecules.
Resolves #1232 
Resolves #1219 
Re-enabling previously skipped test for setting up bace system with spectator molecule.
```
Regression error when setting up systems with spectator molecules has been fixed by avoiding early and unnecessary calls to setup methods.
```
> Fix spectator support

- docs/changelog.rst
> Change log for 0.10.3 release

- perses/samplers/samplers.py
* Off by a_n.max() for the final value, needs to be added back in after the call to log
* Use the scipy.special.logsumexp implementation (used elsewhere) rather than re-implement
Doesn't look like `MultiTargetDesign` is used, so feel free to close this PR. Just happened to see the bug when reading the code. 
Noticed that a custom implementation of logsumexp was incorrect, as it didn't add back in `a_n.max()`.
Incorrect implementation, will produce non-normalized log probabilities for the class `MultiTargetDesign`
No associated case
Tested by the following python script
```
import numpy as np
from numpy.typing import NDArray
from scipy.special import logsumexp
def old_log_sum_exp(vals: NDArray):
return np.log(np.sum(np.exp(vals - vals.max())))
rng = np.random.default_rng(2023)
log_prob = …
```
> Fix incorrect implementation of logsumexp
