.travis.yml, attic/geometry_attic.py, devtools/conda-recipe/meta.yaml, perses/rjmc/geometry.py, perses/tests/test_geometry_engine.py
Beginning of initial implementation of direct switching between compounds/mutations. Currently getting together the `FFGeometryEngine` (so named because it uses forcefield data to propose geometries), followed by the proposal system for small molecules and then a script to run it.
=> Implementing geometry engine

devtools/conda-recipe/meta.yaml, devtools/travis-ci/install.sh, examples/rjmc/run_example.py, perses/__init__.py, perses/annihilation/alchemical_engine.py, perses/annihilation/ncmc_switching.py
I've started a draft of the NCMC deletion/insertion, but have a few questions about how we want `NCMCEngine` to work:
* Is the expectation that `NCMCEngine` is an abstract base class and we will implement subclasses that would have different behaviors?
* We also need the temperature to compute log acceptance probability contributions; perhaps we want to pass a `ThermodynamicState` to the constructor of these objects?
* The 'alchemical_protocol' isn't the same as the YANK discrete alchemical state protocol: 
Here, it's a time-dependent NCMC switching protocol for the alchemical parameters, which are encoded by a dict of switching functions, like `{ 'lambda_sterics' : 'lambda', 'lambda_angles' : 'lambda^2' }`, the number of switching steps `nsteps`, and the `timestep` for velocity Verlet …
=> [WIP] Started draft of NCMC deletion/insertion

examples/rjmc/run_example.py, perses/__init__.py, perses/annihilation/alchemical_engine.py, perses/annihilation/ncmc_switching.py, perses/bias/bias_engine.py, perses/rjmc/geometry.py, perses/rjmc/topology_proposal.py
This PR fixes `run_example.py` to comply with the new API. It also tidies up some other miscellaneous details.
=> [WIP] Fixing run example, etc.

devtools/conda-recipe/meta.yaml, perses/tests/test_geometry_engine.py
Updating the geometry engine test.
=> fixing geometry engine test

perses/annihilation/alchemical_engine.py, perses/tests/test_geometry_engine.py
Addresses the imports issue in #22
=> Fix imports issue

perses/rjmc/topology_proposal.py
Looks like I wanted a property to return itself. This PR is a fix to #34
=> Fix infinite recursion error

.travis.yml, devtools/conda-recipe/meta.yaml, examples/rjmc/run_example.py, perses/annihilation/ncmc_switching.py, perses/rjmc/topology_proposal.py, perses/tests/test_ncmc_integrator.py, perses/tests/test_sampler.py
Apparently, I forgot there was a `run_example.py` in the `examples/` folder. I'm going to restart building the skeleton thing based on that. I've put it here as a test, and will refactor it to also use empty classes (nonetheless, it will be nice to have an example that actually does something). In the process of that, I noticed a couple things:
* `NCMCEngine` is directly derived from `object`. There is nothing wrong with that, other than that it can't be used in the skeleton. So, I've added a base class--I will flesh it out as needed to make the skeleton work.
* The tests are now failing--looks like there's something wrong with the `GeometryEngine` test itself. I will remedy that in this PR.
* I'm going to try to get the openeye tests to be skipped for PRs from forks.
* Since this is the …
=> Basic run test, etc.

.travis.yml, devtools/conda-recipe/meta.yaml, perses/annihilation/__init__.py, perses/rjmc/geometry.py, perses/tests/test_geometry_engine.py
I noticed both `openmm` and `openmm-dev` were dependencies, as well as `parmed` and `parmed-dev`.  Trying to eliminate this and debug the py34 issues.
=> Fix py34 issues

perses/rjmc/topology_proposal.py, perses/tests/test_elimination.py, perses/tests/test_sampler.py, perses/tests/test_topology_proposal.py
This is the refactor of the small molecule proposal engine stuff that we discussed earlier. I've created a new `SystemGenerator` that uses the new `ForceField` stuff. Will now refactor the `ProposalEngine`s to get rid of tleap and simplify (as well as test). Also on the agenda for this PR is randomly selecting an alignment.
=> Refactor small molecule ProposalEngines

perses/rjmc/topology_proposal.py
Two minor changes:
* Removed `beta` from proposals and proposal engines (addressing #91)
* Added `ffxmls` property to `SystemGenerator` to assist in #95
=> Remove beta; add property to SystemGenerator

perses/rjmc/topology_proposal.py
I was going to do this in the geometry PR but my git-fu is not as strong as I would like. This should be a quick PR to shore up some issues identified in the course of #92 .
=> Fix proposal engine (minor things)

perses/rjmc/topology_proposal.py
Addresses #102 and removes `current_positions` arguments from `ProposalEngine`, `SmallMoleculeSetProposalEngine`, and `TopologyProposal`.
=> Fix proposal engines

perses/rjmc/geometry.py, perses/tests/test_geometry_engine.py
This PR will 
* Complete the `GeometryEngine` tests
* Fix any test failures
* Return to sampling torsions from a pdf
Right now, the openeye problem seems to have reared its head again.
=> Geometry Engine tests and cleanup

perses/rjmc/topology_proposal.py, perses/tests/test_samplers.py, perses/tests/testsystems.py
Fixed atom mapping to account for the environment. `GeometryEngine` needs some fixes still regarding eligible torsions. Those are next.
=> Fix atom map

perses/samplers/samplers.py
I broked it.  This unbreaks it.
=> Fix for missing kT

perses/samplers/samplers.py, perses/tests/testsystems.py
This fixes a number of issues with the samplers, including a quick fix for #133.
=> Bugfixes for samplers

perses/rjmc/geometry.py, perses/tests/test_geometry_engine.py
Still have a few things to do. I've written code to extract topological torsions from parmed. I need to get these into the proposal/logp bits, as well as allow calculation of improper torsions.
=> Make proposal based on topological torsions

perses/data/gaff-valence-only.xml, perses/rjmc/geometry.py, perses/rjmc/topology_proposal.py, perses/samplers/samplers.py, perses/tests/test_geometry_engine.py, perses/tests/test_samplers.py, perses/tests/testsystems.py
This test will check that we get appropriate statistics (equal sampling) of molecules with only valence terms.
=> Started work on test of alkanes with only valence energy terms

perses/rjmc/geometry.py, perses/tests/test_geometry_engine.py
Potentially WIP, though it does work on my machine.
=> Fix the geometry logp_reverse by copying coordinates.

perses/annihilation/ncmc_switching.py, perses/rjmc/topology_proposal.py, perses/tests/test_samplers.py
Ok, this is marked as WIP but hopefully it will pass sufficient tests that we can merge it. I am now proposing molecules with a probability proportional to the maximum* number of atoms in common, with 0 probability for remaining in the current state and 0 for transitioning to a state with no common atoms.
*MCSS returns multiple matches.
=> Fix atom mapping, proposal

perses/tests/test_samplers.py, perses/tests/testsystems.py
This should greatly reduce travis testing time.
=> Drastically curtail number of iterations for samplers tests

perses/annihilation/ncmc_switching.py, perses/tests/utils.py
=> Fix reporting of energy components during NCMC

perses/annihilation/ncmc_switching.py, perses/rjmc/geometry.py, perses/rjmc/topology_proposal.py, perses/tests/test_geometry_engine.py, perses/tests/testsystems.py
This PR features/will feature a few improvements:
* Addition of a torsion term to non-rotatable bonds to assist in ring closure.
* Computation of internal coordinates via OpenEye (if this is faster, which it probably is)
* Possible other speedups (such as omitting irrelevant atoms from the `System` that `GeometryEngine` uses).
=> [WIP] Add torsions for ring closure

perses/rjmc/geometry.py, perses/tests/test_geometry_engine.py
This adds writing of atomwise multi-model PDB files for both forward and reverse proposals.
=> Write atomwise PDB file for both forward and reverse geometry proposals

devtools/conda-recipe/meta.yaml, perses/data/T4-inhibitors.xml, perses/data/kinase-inhibitors.xml, perses/rjmc/coordinate_numba.py, perses/rjmc/geometry.py, perses/rjmc/topology_proposal.py, perses/tests/test_geometry_engine.py
I'm adding additional tests for the `GeometryEngine` here. I've added tests that propose all lysozyme ligands to each other, as well as all kinase inhibitor ligands to each other.
=> Geometry testsystems

devtools/conda-recipe/meta.yaml, setup.py
Added numba as a dependency (didn't before because of weird git conflicts).
=> Fix dependency

.travis.yml, perses/annihilation/ncmc_switching.py, perses/rjmc/topology_proposal.py, perses/samplers/samplers.py, perses/tests/test_elimination.py, perses/tests/test_geometry_engine.py
Working on speeding up alchemical elimination tests.
=> Speed up alchemical elimination tests

devtools/travis-ci/install.sh, perses/rjmc/geometry.py, perses/rjmc/topology_proposal.py, perses/tests/test_geometry_engine.py, perses/tests/test_samplers.py, perses/tests/test_topology_proposal.py, perses/tests/testsystems.py
Fixed a couple of issues, still have a couple more to go. WIP, hopefully can fix these today.
=> Fixing Geometry errors

perses/rjmc/geometry.py, perses/rjmc/topology_proposal.py, perses/tests/test_elimination.py
This wraps `print` statements in `if self.verbose:` checks.
=> [WIP] Protect print statements with self.verbose check

perses/annihilation/ncmc_switching.py
Attempt to address slow NCMC performance noted in #192 by using loops in `CustomIntegrator` instead of explicitly unrolling loop in number of steps.
=> Speed up NCMC switching by using loop inside CustomIntegrator

perses/rjmc/geometry.py, perses/tests/test_geometry_engine.py
This is complete. Just going to wait for the tests and fix anything that comes up.
=> Add sterics to geometry

perses/annihilation/ncmc_switching.py, perses/rjmc/geometry.py, perses/tests/test_elimination.py
cc: #203 and #202 
I'm temporarily reverting the change that set `alchemical_angles = True` since this doesn't seem to be working as expected. I will debug this in https://github.com/choderalab/alchemy now, but this change can be reviewed and merged.
We should never allow `lambda_bonds` or `lambda_angles` to be zero, so I have also changed the `default_functions` to only let this drop to 0.1.
=> Don't alchemically soften angles until we can figure out why this is broken

perses/data/constant-pH/imidazole/generate-protomers-from-smiles.py
Addressing https://github.com/choderalab/perses/issues/216
=> Fixing prints

perses/annihilation/ncmc_switching.py
Creating the option in `NCMCEngine` to take multiple steps to propagate at each lambda step.
@pgrinaway
=> Propagation steps

perses/rjmc/topology_proposal.py
This is a PR for @juliebehr's changes to MCSS for `PointMutationEngine`.
I'm testing this right now.
=> [WIP] PointMutationEngine modifications to MCSS

perses/rjmc/topology_proposal.py, perses/tests/test_topology_proposal.py
Heavy Degree alone was insufficient to prevent CB from becoming HA
=> Match atomic number in amino acid MCSS

perses/rjmc/topology_proposal.py, perses/tests/testsystems.py
Tiny change for clarity of output
=> Make chemical_state_key 'WT' instead of empty

.travis.yml, perses/analysis/analysis.py, perses/tests/test_analysis.py, perses/tests/testsystems.py
This fixes an issue in which only python 2.7 was being tested.
=> Fix travis so that proper Python version is tested

devtools/conda-recipe/meta.yaml, perses/analysis/analysis.py, perses/rjmc/geometry.py, perses/storage/movie.py, perses/storage/storage.py, perses/tests/test_storage.py, perses/tests/testsystems.py, setup.py
This adds the writing of positions and topologies to the storage layer.
TODO:
=> Add writing of positions and topology to storage layer

perses/samplers/samplers.py, perses/storage/storage.py, perses/tests/test_storage.py, perses/tests/testsystems.py
=> Fix object storage for python 3

README.md, devtools/travis-ci/install.sh, perses/samplers/samplers.py
This PR:
* Fixes the Jenkins badge
* Removes the extraneous minimization code that was used for geometry debugging and caused problems with constraints. (#256)
=> Fix badge and remove some minimization code

perses/rjmc/topology_proposal.py, perses/tests/test_topology_proposal.py
A `modeller` object was previously instantiated and passed around between the internal functions of the `PolymerProposalEngine`s, but it wasn't doing anything -- in all cases the `modeller.topology` was acted on directly, and the `modeller` is therefore unnecessary.
=> Remove Modeller from Topology Proposal Engines

devtools/travis-ci/install.sh
=> Remove version constraint as conda has now fixed the issue

perses/annihilation/ncmc_switching.py
I think this should fix the NCMC issues we previously had with the symmetric protocol (which we had disabled before now). The integrator structure for both VVVR and GHMC have been overhauled, and protocol and shadow work are also separately accumulated now.
=> Overhaul NCMC integrators

perses/samplers/samplers.py
This is the simplest possibility from https://github.com/choderalab/perses/issues/225#issuecomment-253998035
=> MCMC sampler now adds a barostat if pressure is specified

examples/abl-src-selectivity/abl_src_affinity.py, examples/abl-src-selectivity/selectivity.py
Fixed an API issue and also added in netCDF storage. This is ready to merge once someone looks at it!
=> updating to a working selectivity script

.travis.yml, perses/rjmc/topology_proposal.py, perses/tests/test_analysis.py, perses/tests/test_elimination.py, perses/tests/test_geometry_engine.py, perses/tests/test_samplers.py, perses/tests/test_topology_proposal.py
=> Try drastically simplifying travis

perses/rjmc/topology_proposal.py, perses/tests/testsystems.py
This PR brings in the bugfix commit in `protonation`. It has one extra commit (see description) because of a mistake I made while resolving a conflict.
=> Small molecule bugfix

perses/analysis/analysis.py, perses/annihilation/ncmc_switching.py, perses/storage/storage.py, perses/tests/testsystems.py
This also fixes some minor bugs in NCMC snapshot writing.
=> Add trajectory retrieval and writing to storage layer

perses/analysis/analysis.py, perses/annihilation/ncmc_switching.py, perses/annihilation/relative.py, perses/samplers/samplers.py, perses/tests/benchmark.py, perses/tests/testsystems.py
Extracting changes in the `hybrid-tests` branch that are independent to testing hybrid builder; here: introduction of / history of changes to the `benchmark.py` script
Opening PR to start travis now; https://github.com/choderalab/perses/pull/285 should be merged first
(If tests fail, it's probably because fixes that already exist in `hybrid-tests` were missing in creating this separate branch; I'll keep an eye on them to make sure everything runs independently here but they're probably nothing to worry about)
=> Introduction of Benchmark (cherry picking from hybrid-tests)

perses/analysis/analysis.py, perses/annihilation/ncmc_switching.py, perses/annihilation/relative.py, perses/rjmc/topology_proposal.py, perses/samplers/samplers.py, perses/tests/benchmark.py, perses/tests/test_elimination.py, perses/tests/testsystems.py
PropaneTestSystem previous lived only in `hybrid-tests`
=> PropaneTestSystem -- cherry picking from hybrid-tests

devtools/conda-recipe/meta.yaml
Pinning numpy as specified in #314
=> Pin numpy to 1.10.*

perses/tests/test_elimination.py
=> Ensure logP values are printed on test_elimination test failures

LICENSE, README.md
and update README to link to the MIT license
=> insert license text

docs/annihilation.rst
This PR will provide documentation for the `HybridTopologyEngine`.
=> Hybrid topology documentation

perses/distributed/relative_setup.py
=> Use linear lambda protocol in relative free energy application

perses/distributed/relative_setup.py
The removed function no longer serves any purpose.
=> Remove generate_vacuum function

.travis.yml, devtools/conda-recipe/meta.yaml, devtools/travis-ci/after_success.sh, devtools/travis-ci/install.sh, perses/tests/test_elimination.py, perses/tests/test_ncmc_integrator.py
Just trying to disable the slow tests. Not sure why `skipIf` isn't skipping some tests...
=> Disable slow tests and switch to py35 and py36

perses/distributed/relative_setup.py
Also add comment to docstring. Testing locally now.
=> Increase default padding to 9A

perses/annihilation/new_relative.py, perses/distributed/feptasks.py, perses/distributed/relative_setup.py
Add endpoint perturbations to reweight to the alchemically-unmodified system.
=> Endpoint perturbation

perses/annihilation/new_relative.py, perses/tests/test_hybrid_builder.py
Addresses the second bug in #403
=> Fix typo in atom map

perses/distributed/feptasks.py, perses/distributed/relative_setup.py
Should address #400 by requiring significantly less memory per trajectory.
=> Strip water from trajectories returned by tasklets

perses/rjmc/geometry.py
The most verbose stuff is relegated to the level "debug," and the rest
is in "INFO." The logger name used is "geometry."
=> Change print statements to logger statements

examples/relative_hydration.py, perses/annihilation/ncmc_switching.py, perses/samplers/samplers.py
=> Have OpenMM return the PBC wrapped coordinates for final outputs.

.travis.yml, devtools/conda-recipe/meta.yaml, perses/rjmc/topology_proposal.py, perses/storage/storage.py, perses/tests/test_topology_proposal.py, perses/tests/testsystems.py
=> Always use canonical isomeric SMILES with explicit hydrogens

perses/tests/test_hybrid_builder.py
Added two overlap tests. Neither are running on travis, since even with the pentane <-> butane system, the build times out.
=> Overlap test

.travis.yml, Dockerfile, devtools/conda-recipe/meta.yaml
To simplify debugging and provision of the code in this repo, this PR contains a Dockerfile along with some updates to conda dependencies. Right now, the user would still need to provide an OpenEye license (until #342 is resolved) to use most of the code. Marked WIP because I need to make sure this actually builds correctly (it did before, but without the required dependencies that I've now added).
=> Container infrastructure

perses/dispersed/feptasks.py, perses/dispersed/relative_setup.py, perses/tests/test_relative_setup.py
There was a bug stemming from the fact that under the previous design, a different quantity was used to specify the work write interval. This PR fixes that bug, as well as adds a test to check that the dimensions of the work writeout are correct.
=> Fix write interval

analyse_sams_convergence.py, devtools/conda-recipe/meta.yaml, examples/cdk2-example/cdk2_setup.yaml, hybrid_sams_sampler_test.py, perses/annihilation/new_relative.py, perses/data/cdk2-example/cdk2_setup.yaml, perses/dispersed/feptasks.py, perses/dispersed/relative_setup.py, perses/rjmc/topology_proposal.py, perses/tests/test_relative_setup.py, perses/tests/test_topology_proposal.py, perses/tests/utils.py, scripts/setup_relative_calculation.py
This PR contains a set of improvements including SAMS support, as well as additional yaml options and the ability to rapidly record shadow work.
=> SAMS sampler and other improvements

examples/cdk2-example/cdk2_setup.yaml, perses/annihilation/new_relative.py, perses/dispersed/relative_setup.py, scripts/setup_relative_calculation.py
Fixes state 0 lambda being set to 1, softcore method to amber, online analysis, and adding more support for sams implementation.
=> Sams support for use-nonbonded-offset PR

.travis.yml, devtools/travis-ci/install.sh, perses/annihilation/new_relative.py
This incorporates changes to use the new API https://github.com/pandegroup/openmm/pull/2119
=> Explicitly declare new global parameter for NonbondedForce

perses/annihilation/ncmc_switching.py, perses/annihilation/new_relative.py
This should fix the issue cited [here](https://github.com/pandegroup/openmm/issues/2185#issuecomment-428426529) by @jchodera .
=> [WIP] Use delta function in hybrid topology

perses/annihilation/new_relative.py, perses/rjmc/topology_proposal.py, perses/tests/test_hybrid_builder.py, perses/tests/utils.py
This PR coalesces debugging efforts into a single branch.
=> Coalesce alchemical debugging efforts into one branch

perses/annihilation/new_relative.py, perses/rjmc/geometry.py, perses/tests/test_RJMC_vacuum.py
this function previously proposed atoms out of order, resulting in very large work values.
=> fix to the _propose_atoms_in_order to ensure correct placement order

perses/app/relative_setup.py, perses/app/setup_relative_calculation.py, perses/rjmc/geometry.py
last pr before `mod_refactoring` can be deleted.  adding neglected_angles option in `.yaml` file.
=> placing 'neglect_angles' option into yaml and setup default to 'False'.

perses/rjmc/topology_proposal.py, perses/tests/test_topology_proposal.py, perses/tests/utils.py
merging Dom's mapping improvements into branch with coordinates minimised
=> Atom mapping

perses/annihilation/lambda_protocol.py, perses/app/setup_relative_calculation.py, perses/tests/test_lambda_protocol.py
changing LambdaProtocol to take a single parameter that is either a string or dict
=> [MRG] Changing LambdaProtocol init function

perses/app/setup_relative_calculation.py, perses/samplers/multistate.py
passing LambdaProtocol into HybridXSampler classes, so that they can be used when setting the alchemical variables of the state.
These changes were made previously, but have been lost in the tangle of branches
=> [WIP] adding changes that were missed by branches being a mess

.gitignore, .idea/vcs.xml
Removing erroneously added directory and adding `.gitignore` file,
=> [MRG] .gitignore

perses/annihilation/lambda_protocol.py, perses/app/relative_setup.py, perses/app/setup_relative_calculation.py, perses/dispersed/feptasks.py, perses/rjmc/geometry.py, perses/rjmc/topology_proposal.py
reorganization and update of neq switching for a more robust/modular workflow; also faster with dask
=> refactoring neq_switching for adaptability

perses/app/setup_relative_calculation.py, perses/dispersed/parallel.py, perses/dispersed/smc.py, perses/dispersed/utils.py, perses/tests/test_parallel.py, perses/tests/test_smc.py, perses/tests/testsystems.py
kinase problem has to be fixed before merging with master
=> [WIP] place `simulation` objects into `Experiments`

devtools/test.smi, perses/analysis/load_simulations.py, perses/annihilation/relative.py, perses/app/relative_setup.py, perses/app/setup_relative_calculation.py, perses/dispersed/parallel.py, perses/dispersed/smc.py, perses/dispersed/utils.py, perses/rjmc/topology_proposal.py, perses/samplers/multistate.py, perses/samplers/samplers.py, perses/tests/test.smi, perses/tests/test_geometry_engine.py, perses/tests/test_parallel.py, perses/tests/test_smc.py, perses/tests/testsystems.py, perses/utils/smallmolecules.py
This PR:
* adds in analysis code
* colors residue mapping
* tidies the treatment of multistate endstates and increases consistency between SAMS and REPEX.
=> Changing treatment of endstates

.travis.yml, devtools/conda-recipe/meta.yaml, perses/utils/openeye.py
@hannahbrucemacdonald: This may be why you're having trouble with #622
=> Update travis tests for new openmm-forcefields package to fix failing travis tests

.travis.yml, devtools/conda-recipe/meta.yaml, perses/utils/openeye.py
=> Revert "Update travis tests for new openmm-forcefields package to fix failing travis tests"

perses/analysis/load_simulations.py, perses/app/setup_relative_calculation.py, perses/utils/smallmolecules.py, setup.py
=> [WIP] small improvements to the analysis code

perses/app/relative_setup.py, perses/app/setup_relative_calculation.py
Is there something I also need to do with the endstates if we are doing reaction-field? Just toggle them off?
=> 🚀  exposing nonbonded_method expression

perses/app/setup_relative_calculation.py, setup.py
=> Fixing setup_relative_calculation

examples/rjmc/run_example.py, perses/analysis/load_simulations.py, perses/app/relative_setup.py, perses/app/setup_relative_calculation.py, perses/samplers/multistate.py, perses/samplers/samplers.py
Adding docstrings and making everything a bit nicer.
=> Code cleanup

perses/annihilation/relative.py, perses/app/setup_relative_calculation.py, perses/rjmc/geometry.py, perses/tests/utils.py
… rather than abs. diffenergy validation done on CUDA-double, check changed to energy ratio,…
=> [READY! 💯] cuda double and energy ratio for check

perses/rjmc/topology_proposal.py
Closes #651 by checking atom count after hydrogen exceptions
=> Checks the maximum number of atoms mapped possible after hydrogen exception step

perses/rjmc/topology_proposal.py
=> fixing mapping strategy

.github/workflows/CI.yaml, devtools/conda-recipe/meta.yaml, perses/rjmc/topology_proposal.py, perses/tests/test_topology_proposal.py, setup.py
fix `test_topology_proposal/test_propose_self` so that the insulin template doesn't choose a cysteine residue (which has a disulfide) at random
=> test_topology fix

perses/tests/test_topology_proposal.py
trying to fix stochastic insulin test
=> fix_insulin

perses/app/fah_generator.py, perses/app/setup_relative_calculation.py
=> [READY] Fixing timestep

perses/app/setup_relative_calculation.py
flipping conditional statement for `remove_constraiint`
=> [READY] flip constraint conditional statement

README.md
Once I merge this PR into master I will tag and cut a new release, I am using this PR to make some small changes.
=> Release 0.9.0

perses/app/relative_setup.py, perses/app/setup_relative_calculation.py, perses/tests/test_relative.py, perses/tests/test_relative_setup.py
=> removed atom_map from FEP constructor and updated tests

perses/app/relative_point_mutation_setup.py, perses/data/ala_vacuum.pdb, perses/tests/test_relative_point_mutation_setup.py
We still need to figure out the root cause but this PR sets the default temperature back to 300 K (which reverts PR #783 ) and also adds a quick test that will help catch regressions.
=> Quick fix for issue 802

docs/installation.rst
=> Update installation instructions

.github/workflows/CI.yaml, devtools/conda-envs/test_env.yaml
just a quick test to see if this speeds up running our tests
=> run tests in parallel

.github/pull_request_template.md, docs/changelog.rst, docs/index.rst
This PR will be used to update the change log and when merged will represent the 0.9.1 release.
=> Release 0.9.1

docs/changelog.rst
Bugfix release of version 0.9.4
#938 
#909 
#944 
#934
=> Release 0.9.4

CITATION.cff
Add middle initials to `given-names` field.
Resolves #???
```
```
=> Fix citation file

.github/workflows/CI.yaml, perses/app/setup_relative_calculation.py, perses/tests/test_cli.py
=> Improve CI speed

examples/kinase-neq-switching/run_example.py, examples/protein-ligand/cli/protein-ligand.yaml, perses/app/relative_setup.py, perses/data/bace-example/bace_setup.yaml, perses/data/cdk2-example/cdk2_setup_neq.yaml, perses/data/cdk2-example/cdk2_setup_repex.yaml, perses/tests/test_cli.py, perses/tests/test_resume.py
=> Updates forcefield recommendation to use openff-2.0.0 instead of openff-1.0.0

.github/workflows/self-hosted-gpu-test.yml, perses/tests/test_GPU.py
=> sync gh-ci and aws-ci yaml

perses/app/setup_relative_calculation.py
We are removing the perses-relative tool in a later release.
We are switching to use `perses-cli` and want to tell users about the switch.
Resolves #1014 
```
```
=> Add Deprecation Warning

.github/workflows/self-hosted-gpu-test.yml
=> skip slow tests that are failing, will debug them on lilac

docs/changelog.rst
Changelog for bugfix release 0.10.1.
Please check `changelog.rst` for detailed information.
=> Bugfix Release 0.10.1

devtools/conda-envs/test_env.yaml
Breaking changes coming in pymbar 4
Resolves #???
```
```
=> pin pymbar to stay on 3.x version

.github/workflows/CI.yaml, devtools/conda-envs/test_env.yaml
=> add python 3.10 to CI

devtools/conda-envs/test_env.yaml
=> Pin to older openff-toolkit until we get openmmtools fixed

docker/Dockerfile-nvidia-11
This PR makes a few tiny changes to improve the overall quality of the docker image 🐳 . For reference more annotations can be found [here](https://github.com/opencontainers/image-spec/blob/main/annotations.md)
* Add annotations to the `Dockerfile`
=> feat(docker): Add opencontainers image-spec to `Dockerfile`

benchmarks/run_benchmarks.py, perses/analysis/visualization.py, perses/annihilation/lambda_protocol.py, perses/annihilation/relative.py, perses/annihilation/rest.py, perses/app/cli.py, perses/app/fah_generator.py, perses/app/relative_setup.py, perses/app/setup_relative_calculation.py, perses/dispersed/feptasks.py, perses/dispersed/parallel.py, perses/dispersed/smc.py, perses/dispersed/utils.py, perses/rjmc/atom_mapping.py, perses/rjmc/geometry.py, perses/rjmc/topology_proposal.py, perses/tests/test_atom_mapping.py, perses/utils/openeye.py, perses/utils/url_utils.py
Supersedes #1142 
Thanks @dwhswenson for this!
```
Removed use of `logging.basicConfig`, which was leading to excessive debug output on first import of dependencies.
```
=> Remove basic config

devtools/README.md
Added some notes on our release process.
Resolves #1146 
```
```
=> update release process

.github/workflows/CI.yaml, devtools/conda-envs/test_env.yaml
Going to see if I can get caching to work, this should speed up CI even more.
=> add caching

.github/workflows/CI.yaml
=> enable merge queue

examples/new-cli/README.md
=> Document how to control the log level in the CLI

.github/workflows/CI.yaml, .github/workflows/self-hosted-gpu-test.yml
=> run CI on new 0.10.x branch

examples/dipeptide-mutation-repex-rest/README.md, examples/dipeptide-mutation-repex-rest/configfile, examples/dipeptide-mutation-repex-rest/generate_htfs.py, examples/dipeptide-mutation-repex-rest/hostfile, examples/dipeptide-mutation-repex-rest/run_repex.py
Adding MPI example that does a dipeptide mutation for illustrative purposes on how to use MPI with perses.
Resolves #1224 
```
Added toy example of dipeptide mutation to show MPI capabilities.
```
=> MPI example with dipeptide mutation
